package com.company.order.adapters.outbound.persistence

import com.company.order.domain.models.*
import com.company.order.domain.ports.outbound.OutboxEntry
import com.company.order.domain.ports.outbound.OrderRepositoryPort
import com.company.order.domain.saga.*
import org.jooq.DSLContext
import org.jooq.Record
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.slf4j.LoggerFactory
import java.time.Instant
import java.util.UUID

/**
 * jOOQ-based implementation of the OrderRepositoryPort.
 *
 * Uses jOOQ for type-safe SQL construction, providing compile-time
 * query verification and seamless integration with Kotlin coroutines.
 *
 * Implements the Transactional Outbox pattern: all outbox writes
 * happen within the same database transaction as order mutations.
 */
class JooqOrderRepository(
    private val dsl: DSLContext
) : OrderRepositoryPort {

    private val logger = LoggerFactory.getLogger(JooqOrderRepository::class.java)

    // Table references (would be generated by jOOQ codegen in production)
    private val ORDERS = DSL.table("orders")
    private val ORDER_LINES = DSL.table("order_lines")
    private val SAGA_INSTANCES = DSL.table("saga_instances")
    private val SAGA_STEPS = DSL.table("saga_steps")
    private val OUTBOX = DSL.table("outbox")

    // --- Order CRUD ---

    override suspend fun save(order: Order): Order {
        logger.debug("Saving order: orderId=${order.orderId}")

        dsl.insertInto(ORDERS)
            .set(DSL.field("order_id"), order.orderId)
            .set(DSL.field("customer_id"), order.customerId)
            .set(DSL.field("total_units"), order.total.units)
            .set(DSL.field("total_nanos"), order.total.nanos)
            .set(DSL.field("total_currency_code"), order.total.currencyCode)
            .set(DSL.field("status"), order.status.name)
            .set(DSL.field("payment_id"), order.paymentId)
            .set(DSL.field("cancel_reason"), order.cancelReason)
            .set(DSL.field("idempotency_key"), order.idempotencyKey)
            .set(DSL.field("shipping_line1"), order.shippingAddress.line1)
            .set(DSL.field("shipping_line2"), order.shippingAddress.line2)
            .set(DSL.field("shipping_city"), order.shippingAddress.city)
            .set(DSL.field("shipping_state"), order.shippingAddress.state)
            .set(DSL.field("shipping_postal_code"), order.shippingAddress.postalCode)
            .set(DSL.field("shipping_country_code"), order.shippingAddress.countryCode)
            .set(DSL.field("created_at"), order.createdAt)
            .set(DSL.field("updated_at"), order.updatedAt)
            .set(DSL.field("completed_at"), order.completedAt)
            .onConflict(DSL.field("order_id")).doUpdate()
            .set(DSL.field("status"), order.status.name)
            .set(DSL.field("total_units"), order.total.units)
            .set(DSL.field("total_nanos"), order.total.nanos)
            .set(DSL.field("payment_id"), order.paymentId)
            .set(DSL.field("cancel_reason"), order.cancelReason)
            .set(DSL.field("updated_at"), order.updatedAt)
            .set(DSL.field("completed_at"), order.completedAt)
            .execute()

        // Save reservation IDs as a comma-separated list
        if (order.reservationIds.isNotEmpty()) {
            dsl.update(ORDERS)
                .set(DSL.field("reservation_ids"), order.reservationIds.joinToString(","))
                .where(DSL.field("order_id").eq(order.orderId))
                .execute()
        }

        // Save line items
        dsl.deleteFrom(ORDER_LINES)
            .where(DSL.field("order_id").eq(order.orderId))
            .execute()

        for (line in order.lines) {
            dsl.insertInto(ORDER_LINES)
                .set(DSL.field("order_id"), order.orderId)
                .set(DSL.field("product_id"), line.productId)
                .set(DSL.field("product_name"), line.productName)
                .set(DSL.field("quantity"), line.quantity)
                .set(DSL.field("unit_price_units"), line.unitPrice.units)
                .set(DSL.field("unit_price_nanos"), line.unitPrice.nanos)
                .set(DSL.field("unit_price_currency"), line.unitPrice.currencyCode)
                .set(DSL.field("line_total_units"), line.lineTotal.units)
                .set(DSL.field("line_total_nanos"), line.lineTotal.nanos)
                .set(DSL.field("line_total_currency"), line.lineTotal.currencyCode)
                .execute()
        }

        return order
    }

    override suspend fun findById(orderId: String): Order? {
        logger.debug("Finding order by ID: orderId=$orderId")

        val record = dsl.selectFrom(ORDERS)
            .where(DSL.field("order_id").eq(orderId))
            .fetchOne() ?: return null

        val lines = dsl.selectFrom(ORDER_LINES)
            .where(DSL.field("order_id").eq(orderId))
            .orderBy(DSL.field("product_id"))
            .fetch()
            .map { mapToOrderLine(it) }

        return mapToOrder(record, lines)
    }

    override suspend fun findByCustomer(
        customerId: String,
        pageSize: Int,
        cursor: String?,
        sortBy: SortField
    ): Page<Order> {
        val sortField = when (sortBy) {
            SortField.CREATED_AT_DESC -> DSL.field("created_at").desc()
            SortField.CREATED_AT_ASC -> DSL.field("created_at").asc()
            SortField.UPDATED_AT_DESC -> DSL.field("updated_at").desc()
            SortField.TOTAL_DESC -> DSL.field("total_units").desc()
        }

        var query = dsl.selectFrom(ORDERS)
            .where(DSL.field("customer_id").eq(customerId))

        // Cursor-based pagination using created_at timestamp
        if (cursor != null) {
            val cursorTime = Instant.parse(String(java.util.Base64.getDecoder().decode(cursor)))
            query = query.and(DSL.field("created_at").lt(cursorTime))
        }

        val records = query.orderBy(sortField)
            .limit(pageSize + 1)
            .fetch()

        val hasMore = records.size > pageSize
        val items = records.take(pageSize).map { record ->
            val lines = dsl.selectFrom(ORDER_LINES)
                .where(DSL.field("order_id").eq(record.get(DSL.field("order_id", String::class.java))))
                .fetch()
                .map { mapToOrderLine(it) }
            mapToOrder(record, lines)
        }

        val nextCursor = if (hasMore && items.isNotEmpty()) {
            java.util.Base64.getEncoder().encodeToString(
                items.last().createdAt.toString().toByteArray()
            )
        } else null

        return Page(
            items = items,
            totalCount = items.size.toLong(), // Approximate; exact count requires separate query
            cursor = nextCursor,
            hasMore = hasMore
        )
    }

    override suspend fun findByStatus(status: OrderStatus, pageSize: Int, cursor: String?): Page<Order> {
        var query = dsl.selectFrom(ORDERS)
            .where(DSL.field("status").eq(status.name))

        if (cursor != null) {
            val cursorTime = Instant.parse(String(java.util.Base64.getDecoder().decode(cursor)))
            query = query.and(DSL.field("created_at").lt(cursorTime))
        }

        val records = query.orderBy(DSL.field("created_at").desc())
            .limit(pageSize + 1)
            .fetch()

        val hasMore = records.size > pageSize
        val items = records.take(pageSize).map { record ->
            val lines = dsl.selectFrom(ORDER_LINES)
                .where(DSL.field("order_id").eq(record.get(DSL.field("order_id", String::class.java))))
                .fetch()
                .map { mapToOrderLine(it) }
            mapToOrder(record, lines)
        }

        val nextCursor = if (hasMore && items.isNotEmpty()) {
            java.util.Base64.getEncoder().encodeToString(
                items.last().createdAt.toString().toByteArray()
            )
        } else null

        return Page(items = items, totalCount = items.size.toLong(), cursor = nextCursor, hasMore = hasMore)
    }

    override suspend fun findByIdempotencyKey(idempotencyKey: String): Order? {
        val record = dsl.selectFrom(ORDERS)
            .where(DSL.field("idempotency_key").eq(idempotencyKey))
            .fetchOne() ?: return null

        val lines = dsl.selectFrom(ORDER_LINES)
            .where(DSL.field("order_id").eq(record.get(DSL.field("order_id", String::class.java))))
            .fetch()
            .map { mapToOrderLine(it) }

        return mapToOrder(record, lines)
    }

    override suspend fun existsByIdempotencyKey(idempotencyKey: String): Boolean {
        return dsl.selectCount()
            .from(ORDERS)
            .where(DSL.field("idempotency_key").eq(idempotencyKey))
            .fetchOne(0, Int::class.java)!! > 0
    }

    // --- Saga State ---

    override suspend fun saveSagaState(saga: SagaInstance): SagaInstance {
        logger.debug("Saving saga state: sagaId=${saga.sagaId}, orderId=${saga.orderId}")

        dsl.insertInto(SAGA_INSTANCES)
            .set(DSL.field("saga_id"), saga.sagaId)
            .set(DSL.field("order_id"), saga.orderId)
            .set(DSL.field("saga_type"), saga.sagaType.name)
            .set(DSL.field("status"), saga.status.name)
            .set(DSL.field("started_at"), saga.startedAt)
            .set(DSL.field("completed_at"), saga.completedAt)
            .set(DSL.field("failure_reason"), saga.failureReason)
            .onConflict(DSL.field("saga_id")).doUpdate()
            .set(DSL.field("status"), saga.status.name)
            .set(DSL.field("completed_at"), saga.completedAt)
            .set(DSL.field("failure_reason"), saga.failureReason)
            .execute()

        // Save/update individual steps
        dsl.deleteFrom(SAGA_STEPS)
            .where(DSL.field("saga_id").eq(saga.sagaId))
            .execute()

        for (step in saga.steps) {
            dsl.insertInto(SAGA_STEPS)
                .set(DSL.field("saga_id"), saga.sagaId)
                .set(DSL.field("step_name"), step.stepName)
                .set(DSL.field("status"), step.status.name)
                .set(DSL.field("started_at"), step.startedAt)
                .set(DSL.field("completed_at"), step.completedAt)
                .set(DSL.field("error_message"), step.errorMessage)
                .set(DSL.field("retry_count"), step.retryCount)
                .set(DSL.field("max_retries"), step.maxRetries)
                .execute()
        }

        return saga
    }

    override suspend fun findSagaByOrderId(orderId: String): SagaInstance? {
        val record = dsl.selectFrom(SAGA_INSTANCES)
            .where(DSL.field("order_id").eq(orderId))
            .orderBy(DSL.field("started_at").desc())
            .limit(1)
            .fetchOne() ?: return null

        val steps = dsl.selectFrom(SAGA_STEPS)
            .where(DSL.field("saga_id").eq(record.get(DSL.field("saga_id", String::class.java))))
            .orderBy(DSL.field("step_name"))
            .fetch()
            .map { stepRecord ->
                SagaStep(
                    stepName = stepRecord.get(DSL.field("step_name", String::class.java)),
                    status = SagaStepStatus.valueOf(stepRecord.get(DSL.field("status", String::class.java))),
                    startedAt = stepRecord.get(DSL.field("started_at", Instant::class.java)),
                    completedAt = stepRecord.get(DSL.field("completed_at", Instant::class.java)),
                    errorMessage = stepRecord.get(DSL.field("error_message", String::class.java)),
                    retryCount = stepRecord.get(DSL.field("retry_count", Int::class.java)) ?: 0,
                    maxRetries = stepRecord.get(DSL.field("max_retries", Int::class.java)) ?: 3
                )
            }

        return SagaInstance(
            sagaId = record.get(DSL.field("saga_id", String::class.java)),
            orderId = record.get(DSL.field("order_id", String::class.java)),
            sagaType = SagaType.valueOf(record.get(DSL.field("saga_type", String::class.java))),
            status = SagaStatus.valueOf(record.get(DSL.field("status", String::class.java))),
            steps = steps,
            startedAt = record.get(DSL.field("started_at", Instant::class.java)),
            completedAt = record.get(DSL.field("completed_at", Instant::class.java)),
            failureReason = record.get(DSL.field("failure_reason", String::class.java))
        )
    }

    override suspend fun findSagasByStatus(status: SagaStatus): List<SagaInstance> {
        val records = dsl.selectFrom(SAGA_INSTANCES)
            .where(DSL.field("status").eq(status.name))
            .fetch()

        return records.map { record ->
            val steps = dsl.selectFrom(SAGA_STEPS)
                .where(DSL.field("saga_id").eq(record.get(DSL.field("saga_id", String::class.java))))
                .fetch()
                .map { stepRecord ->
                    SagaStep(
                        stepName = stepRecord.get(DSL.field("step_name", String::class.java)),
                        status = SagaStepStatus.valueOf(stepRecord.get(DSL.field("status", String::class.java))),
                        startedAt = stepRecord.get(DSL.field("started_at", Instant::class.java)),
                        completedAt = stepRecord.get(DSL.field("completed_at", Instant::class.java)),
                        errorMessage = stepRecord.get(DSL.field("error_message", String::class.java)),
                        retryCount = stepRecord.get(DSL.field("retry_count", Int::class.java)) ?: 0,
                        maxRetries = stepRecord.get(DSL.field("max_retries", Int::class.java)) ?: 3
                    )
                }

            SagaInstance(
                sagaId = record.get(DSL.field("saga_id", String::class.java)),
                orderId = record.get(DSL.field("order_id", String::class.java)),
                sagaType = SagaType.valueOf(record.get(DSL.field("saga_type", String::class.java))),
                status = status,
                steps = steps,
                startedAt = record.get(DSL.field("started_at", Instant::class.java)),
                completedAt = record.get(DSL.field("completed_at", Instant::class.java)),
                failureReason = record.get(DSL.field("failure_reason", String::class.java))
            )
        }
    }

    // --- Transactional Outbox ---

    override suspend fun appendToOutbox(event: OutboxEntry) {
        logger.debug("Appending to outbox: eventId=${event.eventId}, type=${event.eventType}")

        dsl.insertInto(OUTBOX)
            .set(DSL.field("event_id"), event.eventId)
            .set(DSL.field("aggregate_id"), event.aggregateId)
            .set(DSL.field("aggregate_type"), event.aggregateType)
            .set(DSL.field("event_type"), event.eventType)
            .set(DSL.field("payload"), event.payload)
            .set(DSL.field("created_at"), event.createdAt)
            .set(DSL.field("published"), false)
            .set(DSL.field("trace_parent"), event.traceParent)
            .execute()
    }

    override suspend fun readOutbox(limit: Int): List<OutboxEntry> {
        return dsl.selectFrom(OUTBOX)
            .where(DSL.field("published").eq(false))
            .orderBy(DSL.field("created_at").asc())
            .limit(limit)
            .fetch()
            .map { record ->
                OutboxEntry(
                    eventId = record.get(DSL.field("event_id", String::class.java)),
                    aggregateId = record.get(DSL.field("aggregate_id", String::class.java)),
                    aggregateType = record.get(DSL.field("aggregate_type", String::class.java)),
                    eventType = record.get(DSL.field("event_type", String::class.java)),
                    payload = record.get(DSL.field("payload", ByteArray::class.java)),
                    createdAt = record.get(DSL.field("created_at", Instant::class.java)),
                    published = record.get(DSL.field("published", Boolean::class.java)),
                    publishedAt = record.get(DSL.field("published_at", Instant::class.java)),
                    traceParent = record.get(DSL.field("trace_parent", String::class.java))
                )
            }
    }

    override suspend fun markOutboxProcessed(ids: List<String>) {
        if (ids.isEmpty()) return

        dsl.update(OUTBOX)
            .set(DSL.field("published"), true)
            .set(DSL.field("published_at"), Instant.now())
            .where(DSL.field("event_id").`in`(ids))
            .execute()
    }

    // --- Transaction Management ---

    override suspend fun <T> inTransaction(block: suspend () -> T): T {
        return dsl.transactionResult { _ ->
            // In jOOQ, the transaction is managed by the DSLContext
            // The block executes within the transaction boundary
            kotlinx.coroutines.runBlocking { block() }
        }
    }

    // --- Mapping Functions ---

    private fun mapToOrder(record: Record, lines: List<OrderLine>): Order {
        val reservationIdsStr = record.get(DSL.field("reservation_ids", String::class.java)) ?: ""
        val reservationIds = if (reservationIdsStr.isNotBlank()) reservationIdsStr.split(",") else emptyList()

        return Order(
            orderId = record.get(DSL.field("order_id", String::class.java)),
            customerId = record.get(DSL.field("customer_id", String::class.java)),
            lines = lines,
            total = Money(
                units = record.get(DSL.field("total_units", Long::class.java)),
                nanos = record.get(DSL.field("total_nanos", Int::class.java)),
                currencyCode = record.get(DSL.field("total_currency_code", String::class.java))
            ),
            status = OrderStatus.valueOf(record.get(DSL.field("status", String::class.java))),
            shippingAddress = Address(
                line1 = record.get(DSL.field("shipping_line1", String::class.java)),
                line2 = record.get(DSL.field("shipping_line2", String::class.java)),
                city = record.get(DSL.field("shipping_city", String::class.java)),
                state = record.get(DSL.field("shipping_state", String::class.java)),
                postalCode = record.get(DSL.field("shipping_postal_code", String::class.java)),
                countryCode = record.get(DSL.field("shipping_country_code", String::class.java))
            ),
            paymentId = record.get(DSL.field("payment_id", String::class.java)),
            reservationIds = reservationIds,
            createdAt = record.get(DSL.field("created_at", Instant::class.java)),
            updatedAt = record.get(DSL.field("updated_at", Instant::class.java)),
            completedAt = record.get(DSL.field("completed_at", Instant::class.java)),
            cancelReason = record.get(DSL.field("cancel_reason", String::class.java)),
            idempotencyKey = record.get(DSL.field("idempotency_key", String::class.java))
        )
    }

    private fun mapToOrderLine(record: Record): OrderLine = OrderLine(
        productId = record.get(DSL.field("product_id", String::class.java)),
        productName = record.get(DSL.field("product_name", String::class.java)),
        quantity = record.get(DSL.field("quantity", Int::class.java)),
        unitPrice = Money(
            units = record.get(DSL.field("unit_price_units", Long::class.java)),
            nanos = record.get(DSL.field("unit_price_nanos", Int::class.java)),
            currencyCode = record.get(DSL.field("unit_price_currency", String::class.java))
        ),
        lineTotal = Money(
            units = record.get(DSL.field("line_total_units", Long::class.java)),
            nanos = record.get(DSL.field("line_total_nanos", Int::class.java)),
            currencyCode = record.get(DSL.field("line_total_currency", String::class.java))
        )
    )
}
