apiVersion: v1
kind: Service
metadata:
  name: cdc-relay
  labels:
    app.kubernetes.io/name: cdc-relay
    app.kubernetes.io/component: cdc-relay
    app.kubernetes.io/part-of: polyglot-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cdc-relay
  ports:
    - name: http
      port: 8088
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
