apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-overlay
resources:
- ../../base
- ../../platform
namespace: production
commonLabels:
  environment: dev
  app.kubernetes.io/environment: dev
images:
- name: gateway
  newName: ghcr.io/example/gateway
  newTag: dev
- name: identity
  newName: ghcr.io/example/identity
  newTag: dev
- name: catalog
  newName: ghcr.io/example/catalog
  newTag: dev
- name: order
  newName: ghcr.io/example/order
  newTag: dev
- name: payment
  newName: ghcr.io/example/payment
  newTag: dev
- name: notification
  newName: ghcr.io/example/notification
  newTag: dev
- name: analytics
  newName: ghcr.io/example/analytics
  newTag: dev
- name: cdc-relay
  newName: ghcr.io/example/cdc-relay
  newTag: dev
- name: schema-registry
  newName: ghcr.io/example/schema-registry
  newTag: dev
configMapGenerator:
- name: environment-config
  literals:
  - LOG_LEVEL=DEBUG
  - OTEL_TRACES_SAMPLER=always_on
  - OTEL_METRICS_EXPORT_INTERVAL=10000
  - SPIRE_TRUST_DOMAIN=trust.dev.example.org
  behavior: create
