apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/component: payment
    app.kubernetes.io/part-of: polyglot-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payment
        app.kubernetes.io/component: payment
        app.kubernetes.io/part-of: polyglot-microservices
      annotations:
        spiffe.io/inject: "true"
    spec:
      securityContext:
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: payment
      containers:
        - name: payment
          image: polyglot-platform/payment:latest
          ports:
            - name: grpc
              containerPort: 50055
              protocol: TCP
            - name: health
              containerPort: 9091
              protocol: TCP
          env:
            - name: GRPC_PORT
              value: "50055"
            - name: HEALTH_PORT
              value: "9091"
            - name: SPIFFE_ENDPOINT_SOCKET
              value: "unix:///run/spire/sockets/agent.sock"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-gateway.production.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "payment"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
