apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: production
    app.kubernetes.io/part-of: polyglot-microservices
    app.kubernetes.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations: {}
spec:
  finalizers:
    - kubernetes
