"""CDC Relay — Domain Ports"""
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import List
from .models import ConnectorState, ReplicationStatus, StartReplicationRequest


class ReplicationPort(ABC):
    @abstractmethod
    async def start_replication(self, request: StartReplicationRequest) -> ConnectorState: ...
    @abstractmethod
    async def stop_replication(self, connector_name: str) -> ConnectorState: ...
    @abstractmethod
    async def get_replication_status(self, connector_name: str) -> ReplicationStatus: ...
    @abstractmethod
    async def list_connectors(self) -> List[ConnectorState]: ...


class ConnectorRegistryPort(ABC):
    @abstractmethod
    async def create_connector(self, config: dict) -> ConnectorState: ...
    @abstractmethod
    async def delete_connector(self, name: str) -> None: ...
    @abstractmethod
    async def get_connector_status(self, name: str) -> ConnectorState: ...
    @abstractmethod
    async def list_connectors(self) -> List[str]: ...
    @abstractmethod
    async def pause_connector(self, name: str) -> None: ...
    @abstractmethod
    async def resume_connector(self, name: str) -> None: ...
