apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/component: analytics
    app.kubernetes.io/part-of: polyglot-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics
  ports:
    - name: grpc
      port: 50057
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8087
      targetPort: http
      protocol: TCP
