"""
Domain models for the Analytics service.

These models represent the core business concepts of analytics processing,
including metrics, time-series data, reports, and aggregation windows.
All models are pure Python dataclasses with zero external dependencies,
ensuring the hexagonal architecture boundary is strictly maintained.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


class MetricType(str, Enum):
    """Type of metric measurement. Counters track cumulative values that only
    increase (e.g., request count). Gauges track point-in-time values that can
    go up or down (e.g., active connections). Histograms track distributions
    of values across configurable buckets (e.g., request latency)."""
    COUNTER = "COUNTER"
    GAUGE = "GAUGE"
    HISTOGRAM = "HISTOGRAM"


class AggregationFunction(str, Enum):
    """Supported aggregation functions for time-series rollups.
    Sum and count are straightforward. Avg computes the mean.
    Min and max track extremes. P50, P95, P99 compute percentiles
    for latency analysis. Each function determines how raw data points
    are combined within an aggregation window."""
    SUM = "SUM"
    AVG = "AVG"
    MIN = "MIN"
    MAX = "MAX"
    COUNT = "COUNT"
    P50 = "P50"
    P95 = "P95"
    P99 = "P99"


class Granularity(str, Enum):
    """Time-series data granularity for aggregation windows.
    Finer granularities consume more storage but provide better
    resolution for real-time dashboards. Coarser granularities
    are pre-computed as rollups for long-range historical queries."""
    ONE_MINUTE = "1m"
    FIVE_MINUTES = "5m"
    ONE_HOUR = "1h"
    ONE_DAY = "1d"


class ReportType(str, Enum):
    """Types of reports that can be generated by the analytics service.
    Each report type has specific formatting, aggregation, and
    delivery requirements that are handled by the report service."""
    SERVICE_HEALTH = "SERVICE_HEALTH"
    API_PERFORMANCE = "API_PERFORMANCE"
    BUSINESS_METRICS = "BUSINESS_METRICS"
    ERROR_ANALYSIS = "ERROR_ANALYSIS"
    CUSTOM = "CUSTOM"


@dataclass(frozen=True)
class DataPoint:
    """A single time-series data point with timestamp, value, and tags.
    Tags are key-value pairs that enable dimensional queries, such as
    filtering by service name, HTTP method, or error code. DataPoints
    are immutable to prevent accidental modification of historical data."""
    timestamp: datetime
    value: float
    tags: dict[str, str] = field(default_factory=dict)

    def with_tag(self, key: str, value: str) -> "DataPoint":
        """Return a new DataPoint with an additional tag."""
        new_tags = {**self.tags, key: value}
        return DataPoint(timestamp=self.timestamp, value=self.value, tags=new_tags)


@dataclass
class Metric:
    """A named metric with type, tags, and data points.
    Metrics are the fundamental unit of observability data, representing
    measurable quantities like request latency, error rates, or throughput.
    Each metric belongs to a service and has a type that determines how
    its data points are aggregated and queried."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    service: str = ""
    metric_type: MetricType = MetricType.GAUGE
    description: str = ""
    unit: str = ""
    tags: dict[str, str] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class AggregationWindow:
    """Defines a time window for metric aggregation.
    The window determines how raw data points are grouped for rollup
    calculations. Each window has a start time, end time, granularity,
    and the aggregation function to apply within the window."""
    start_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    end_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    granularity: Granularity = Granularity.FIVE_MINUTES
    function: AggregationFunction = AggregationFunction.AVG

    @property
    def duration_seconds(self) -> float:
        """Return the window duration in seconds."""
        return (self.end_time - self.start_time).total_seconds()


@dataclass
class TimeSeries:
    """A sequence of aggregated data points for a specific metric.
    TimeSeries is the primary query result type, representing the
    evolution of a metric over time. Each series has metadata about
    the metric, the aggregation applied, and the data points themselves."""
    metric_name: str = ""
    service: str = ""
    aggregation: AggregationFunction = AggregationFunction.AVG
    granularity: Granularity = Granularity.FIVE_MINUTES
    tags: dict[str, str] = field(default_factory=dict)
    points: list[DataPoint] = field(default_factory=list)

    @property
    def point_count(self) -> int:
        return len(self.points)

    @property
    def is_empty(self) -> bool:
        return len(self.points) == 0

    def latest_value(self) -> Optional[float]:
        """Return the most recent data point value, or None if empty."""
        if self.is_empty:
            return None
        return self.points[-1].value


@dataclass
class Report:
    """A generated analytics report with metadata and data sections.
    Reports can be generated on-demand or scheduled for periodic delivery.
    Each report has a type, time range, and structured data that can be
    exported as JSON, CSV, or PDF depending on the consumer's needs."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    report_type: ReportType = ReportType.SERVICE_HEALTH
    title: str = ""
    time_range_start: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    time_range_end: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    granularity: Granularity = Granularity.ONE_HOUR
    services: list[str] = field(default_factory=list)
    data: dict[str, Any] = field(default_factory=dict)
    format: str = "JSON"  # JSON, CSV, PDF
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    generated_at: Optional[datetime] = None

    def mark_generated(self) -> None:
        """Mark the report as generated with the current timestamp."""
        self.generated_at = datetime.now(timezone.utc)


@dataclass
class Dashboard:
    """Dashboard configuration for real-time metric visualization.
    Dashboards define a set of panels, each displaying one or more
    time-series with specific visualization settings. Dashboards are
    stored in PostgreSQL and served via the gRPC/REST API."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    description: str = ""
    owner: str = ""
    panels: list[dict[str, Any]] = field(default_factory=list)
    refresh_interval_seconds: int = 30
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = None
