apiVersion: v1
kind: Service
metadata:
  name: rl-engine
  labels:
    app.kubernetes.io/name: rl-engine
    app.kubernetes.io/component: rl-engine
    app.kubernetes.io/part-of: polyglot-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rl-engine
  ports:
    - name: http
      port: 8088
      targetPort: http
      protocol: TCP
