apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/component: notification
    app.kubernetes.io/part-of: polyglot-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification
  ports:
    - name: grpc
      port: 50056
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8086
      targetPort: http
      protocol: TCP
