apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: catalog
    app.kubernetes.io/part-of: polyglot-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog
  ports:
    - name: grpc
      port: 50053
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
