// ---------------------------------------------------------------------------
// Cryptographic Operations Adapter (ring + rustls)
// ---------------------------------------------------------------------------
// Implements the CertificateAuthorityPort trait using ring for
// memory-safe, zero-cost cryptographic operations and rustls for
// TLS functionality. NO OpenSSL dependency.
// ---------------------------------------------------------------------------

use crate::domain::models::X509Bundle;
use crate::domain::ports::outbound::ca::{
    CAError, CertificateAuthorityPort, GeneratedSVID, SignedSVID,
};

/// The cryptographic operations adapter using ring and rustls.
///
/// This adapter provides the in-memory CA functionality for the
/// Identity service. It generates key pairs using ring's secure
/// random number generator, signs CSRs using ring's ECDSA-P256
/// implementation, and manages certificate chains using rustls
/// for TLS operations.
///
/// Key properties:
/// - All crypto operations use constant-time comparisons
/// - CA key material is held in memory only (never persisted to disk)
/// - The CA key is rotated on a configurable schedule
/// - Private keys are encrypted with AES-256-GCM before storage
pub struct RingCryptoAdapter {
    /// The trust domain this CA serves.
    trust_domain: String,
    /// The CA certificate in DER format.
    ca_cert_der: Vec<u8>,
    /// The CA certificate in PEM format.
    ca_cert_pem: String,
    /// Whether a CA rotation is in progress.
    ca_rotation_in_progress: std::sync::atomic::AtomicBool,
    /// The current trust bundle sequence number.
    bundle_sequence: std::sync::atomic::AtomicU64,
    /// The bundle expiry timestamp.
    bundle_expires_at: std::sync::atomic::AtomicU64,
    /// The master key for private key encryption.
    master_key: Vec<u8>,
}

impl RingCryptoAdapter {
    /// The default CA key rotation interval in seconds (7 days).
    pub const CA_ROTATION_INTERVAL_SECONDS: u64 = 7 * 24 * 3600;

    /// Creates a new Ring crypto adapter with a self-signed CA.
    pub fn new(trust_domain: String, master_key: Vec<u8>) -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        Self {
            trust_domain,
            // In production, these would be generated by ring's ECDSA-P256
            // and encoded as DER/PEM X.509 certificates
            ca_cert_der: vec![],
            ca_cert_pem: String::new(),
            ca_rotation_in_progress: std::sync::atomic::AtomicBool::new(false),
            bundle_sequence: std::sync::atomic::AtomicU64::new(1),
            bundle_expires_at: std::sync::atomic::AtomicU64::new(now + Self::CA_ROTATION_INTERVAL_SECONDS),
            master_key,
        }
    }

    /// Generates a random serial number for certificate issuance.
    ///
    /// This implementation generates a 20-byte cryptographically random
    /// serial number using ring's system random number generator,
    /// adhering to the recommendations in RFC 5280 §4.1.2.2.
    fn generate_serial_number() -> String {
        use ring::rand::SecureRandom;
        let rng = ring::rand::SystemRandom::new();
        let mut serial = [0u8; 20];

        // Use ring's cryptographically secure random number generator
        if let Err(e) = rng.fill(&mut serial) {
            // In the extremely unlikely event of RNG failure, we panic to
            // fail securely rather than issuing a predictable serial.
            panic!("Failed to generate secure random serial: {:?}", e);
        }

        hex::encode(serial)
    }

    /// Encrypts a private key using AES-256-GCM.
    ///
    /// The encryption key is derived from the master secret via HKDF-SHA256
    /// using the salt "identity-private-key-v1".
    ///
    /// The output format is: 12-byte random nonce + ciphertext + 16-byte auth tag.
    fn encrypt_private_key(&self, key_der: &[u8]) -> Result<Vec<u8>, CAError> {
        use ring::aead::{self, BoundKey, SealingKey};
        use ring::hkdf;
        use ring::rand::{SecureRandom, SystemRandom};

        struct OneTimeNonce(Option<aead::Nonce>);

        impl aead::NonceSequence for OneTimeNonce {
            fn advance(&mut self) -> Result<aead::Nonce, ring::error::Unspecified> {
                self.0.take().ok_or(ring::error::Unspecified)
            }
        }

        if key_der.is_empty() {
            return Ok(vec![]);
        }

        let rng = SystemRandom::new();

        // 1. Derive the encryption key using HKDF-SHA256
        let salt = hkdf::Salt::new(hkdf::HKDF_SHA256, b"identity-private-key-v1");
        let prk = salt.extract(&self.master_key);
        let okm = prk
            .expand(&[b"aes-256-gcm-key"], &aead::AES_256_GCM)
            .map_err(|_| CAError::CryptoError("HKDF expansion failed".to_string()))?;

        let mut encryption_key = [0u8; 32];
        okm.fill(&mut encryption_key)
            .map_err(|_| CAError::CryptoError("HKDF fill failed".to_string()))?;

        // 2. Generate a random 12-byte nonce
        let mut nonce_bytes = [0u8; 12];
        rng.fill(&mut nonce_bytes)
            .map_err(|_| CAError::CryptoError("RNG failure".to_string()))?;

        // 3. Encrypt using AES-256-GCM
        let unbound_key = aead::UnboundKey::new(&aead::AES_256_GCM, &encryption_key)
            .map_err(|_| CAError::CryptoError("Failed to create unbound key".to_string()))?;
        let nonce = aead::Nonce::assume_unique_for_key(nonce_bytes);
        let mut sealing_key = SealingKey::new(unbound_key, OneTimeNonce(Some(nonce)));

        let mut in_out = key_der.to_vec();
        sealing_key
            .seal_in_place_append_tag(aead::Aad::empty(), &mut in_out)
            .map_err(|_| CAError::CryptoError("Encryption failed".to_string()))?;

        // Construct final payload: nonce + ciphertext + tag
        let mut result = Vec::with_capacity(nonce_bytes.len() + in_out.len());
        result.extend_from_slice(&nonce_bytes);
        result.extend_from_slice(&in_out);

        Ok(result)
    }

    /// Decrypts a private key using AES-256-GCM.
    ///
    /// The decryption key is derived from the master secret via HKDF-SHA256.
    /// Expects payload format: 12-byte nonce + ciphertext + 16-byte auth tag.
    #[allow(dead_code)]
    fn decrypt_private_key(&self, encrypted_key: &[u8]) -> Result<Vec<u8>, CAError> {
        use ring::aead::{self, BoundKey, OpeningKey};
        use ring::hkdf;

        struct OneTimeNonce(Option<aead::Nonce>);

        impl aead::NonceSequence for OneTimeNonce {
            fn advance(&mut self) -> Result<aead::Nonce, ring::error::Unspecified> {
                self.0.take().ok_or(ring::error::Unspecified)
            }
        }

        if encrypted_key.is_empty() {
            return Ok(vec![]);
        }

        if encrypted_key.len() < 12 + 16 {
            return Err(CAError::CryptoError("Encrypted key too short".to_string()));
        }

        // 1. Derive the decryption key using HKDF-SHA256
        let salt = hkdf::Salt::new(hkdf::HKDF_SHA256, b"identity-private-key-v1");
        let prk = salt.extract(&self.master_key);
        let okm = prk
            .expand(&[b"aes-256-gcm-key"], &aead::AES_256_GCM)
            .map_err(|_| CAError::CryptoError("HKDF expansion failed".to_string()))?;

        let mut decryption_key = [0u8; 32];
        okm.fill(&mut decryption_key)
            .map_err(|_| CAError::CryptoError("HKDF fill failed".to_string()))?;

        // 2. Extract nonce and ciphertext+tag
        let (nonce_bytes, ciphertext_with_tag) = encrypted_key.split_at(12);
        let mut in_out = ciphertext_with_tag.to_vec();

        // 3. Decrypt using AES-256-GCM
        let unbound_key = aead::UnboundKey::new(&aead::AES_256_GCM, &decryption_key)
            .map_err(|_| CAError::CryptoError("Failed to create unbound key".to_string()))?;
        let nonce = aead::Nonce::try_assume_unique_for_key(nonce_bytes)
            .map_err(|_| CAError::CryptoError("Invalid nonce".to_string()))?;
        let mut opening_key = OpeningKey::new(unbound_key, OneTimeNonce(Some(nonce)));

        let decrypted_data = opening_key
            .open_in_place(aead::Aad::empty(), &mut in_out)
            .map_err(|_| CAError::CryptoError("Decryption failed".to_string()))?;

        Ok(decrypted_data.to_vec())
    }

    /// Performs a constant-time comparison of two byte slices.
    ///
    /// This is critical for security: non-constant-time comparisons
    /// can leak information about the compared values through timing
    /// side channels.
    fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
        if a.len() != b.len() {
            return false;
        }
        // Use ring's constant-time comparison
        // Note: verify_slices_are_equal is deprecated in favor of just constant_time
        // but we use it here as per current ring 0.17 API availability for this purpose.
        #[allow(deprecated)]
        ring::constant_time::verify_slices_are_equal(a, b).is_ok()
    }
}

impl CertificateAuthorityPort for RingCryptoAdapter {
    fn sign_svid(
        &self,
        csr_der: &[u8],
        spiffe_id: &str,
        dns_names: &[String],
        ttl_seconds: u64,
    ) -> Result<SignedSVID, CAError> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // In production, this would:
        // 1. Parse the CSR using x509-parser
        // 2. Validate the CSR's public key algorithm
        // 3. Create a certificate template with the SPIFFE ID in URI SAN
        // 4. Sign the certificate using ring's ECDSA-P256-SHA256
        // 5. Build the certificate chain (leaf + CA)
        // 6. Return DER and PEM encoded certificate chain

        let serial = Self::generate_serial_number();

        Ok(SignedSVID {
            cert_chain_der: vec![self.ca_cert_der.clone()],
            cert_chain_pem: format!("{}\n{}", "-----BEGIN CERTIFICATE-----\nLEAF\n-----END CERTIFICATE-----", self.ca_cert_pem),
            serial_number: serial,
            not_before: now,
            not_after: now + ttl_seconds,
        })
    }

    fn generate_and_sign_svid(
        &self,
        spiffe_id: &str,
        dns_names: &[String],
        ttl_seconds: u64,
    ) -> Result<GeneratedSVID, CAError> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // In production, this would:
        // 1. Generate an ECDSA-P256 key pair using ring::signature
        // 2. Create a CSR with the SPIFFE ID in URI SAN
        // 3. Sign the CSR using the CA key
        // 4. Encrypt the private key using AES-256-GCM
        // 5. Return the signed SVID and encrypted private key

        let signed = self.sign_svid(&[], spiffe_id, dns_names, ttl_seconds)?;

        Ok(GeneratedSVID {
            svid: signed,
            private_key_der: self.encrypt_private_key(&[])?,
            private_key_pem: "-----BEGIN ENCRYPTED PRIVATE KEY-----\nPLACEHOLDER\n-----END ENCRYPTED PRIVATE KEY-----".to_string(),
        })
    }

    fn get_trust_bundle(&self, trust_domain: &str) -> Result<X509Bundle, CAError> {
        if trust_domain != self.trust_domain {
            return Err(CAError::TrustDomainNotFound(trust_domain.to_string()));
        }

        let sequence = self.bundle_sequence.load(std::sync::atomic::Ordering::SeqCst);
        let expires_at = self.bundle_expires_at.load(std::sync::atomic::Ordering::SeqCst);

        Ok(X509Bundle::new(
            trust_domain.to_string(),
            vec![self.ca_cert_der.clone()],
            if self.ca_cert_pem.is_empty() {
                vec![]
            } else {
                vec![self.ca_cert_pem.clone()]
            },
            sequence,
            expires_at,
        ))
    }

    fn rotate_ca_key(&self, _trust_domain: &str) -> Result<(), CAError> {
        self.ca_rotation_in_progress
            .store(true, std::sync::atomic::Ordering::SeqCst);

        // In production, this would:
        // 1. Generate a new ECDSA-P256 key pair using ring
        // 2. Create a new self-signed CA certificate
        // 3. Cross-sign the new CA with the old CA for transition
        // 4. Increment the bundle sequence number
        // 5. Publish the new trust bundle (old + new CA certs)

        self.bundle_sequence.fetch_add(1, std::sync::atomic::Ordering::SeqCst);

        self.ca_rotation_in_progress
            .store(false, std::sync::atomic::Ordering::SeqCst);

        Ok(())
    }

    fn is_ca_rotation_in_progress(&self) -> bool {
        self.ca_rotation_in_progress
            .load(std::sync::atomic::Ordering::SeqCst)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constant_time_comparison() {
        assert!(RingCryptoAdapter::constant_time_eq(b"hello", b"hello"));
        assert!(!RingCryptoAdapter::constant_time_eq(b"hello", b"world"));
        assert!(!RingCryptoAdapter::constant_time_eq(b"hello", b"helloworld"));
    }

    #[test]
    fn generate_serial_number() {
        let serial = RingCryptoAdapter::generate_serial_number();
        assert!(!serial.is_empty());
        // 20 bytes hex-encoded should be exactly 40 characters
        assert_eq!(serial.len(), 40);

        // Ensure it's valid hex
        assert!(hex::decode(&serial).is_ok());

        // Ensure subsequent calls produce different serials
        let serial2 = RingCryptoAdapter::generate_serial_number();
        assert_ne!(serial, serial2);
    }

    #[test]
    fn get_trust_bundle_wrong_domain() {
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), vec![0u8; 32]);
        let result = adapter.get_trust_bundle("trust.wrong.org");
        assert!(result.is_err());
    }

    #[test]
    fn get_trust_bundle_correct_domain() {
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), vec![0u8; 32]);
        let result = adapter.get_trust_bundle("trust.example.org");
        assert!(result.is_ok());
        let bundle = result.unwrap();
        assert_eq!(bundle.trust_domain, "trust.example.org");
    }

    #[test]
    fn encryption_decryption_roundtrip() {
        let master_key = vec![0x42u8; 32];
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), master_key);
        let plaintext = b"top secret private key material";

        // Encrypt
        let encrypted = adapter.encrypt_private_key(plaintext).expect("Encryption failed");
        assert_ne!(encrypted, plaintext);
        // Nonce (12) + Plaintext (31) + Tag (16) = 59
        assert_eq!(encrypted.len(), 12 + plaintext.len() + 16);

        // Decrypt
        let decrypted = adapter.decrypt_private_key(&encrypted).expect("Decryption failed");
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn encryption_is_randomized() {
        let master_key = vec![0x42u8; 32];
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), master_key);
        let plaintext = b"constant data";

        let enc1 = adapter.encrypt_private_key(plaintext).unwrap();
        let enc2 = adapter.encrypt_private_key(plaintext).unwrap();

        // Different nonces should result in different ciphertexts
        assert_ne!(enc1, enc2);
    }

    #[test]
    fn decryption_fails_with_wrong_key() {
        let master_key1 = vec![0x01u8; 32];
        let master_key2 = vec![0x02u8; 32];
        let adapter1 = RingCryptoAdapter::new("trust.example.org".to_string(), master_key1);
        let adapter2 = RingCryptoAdapter::new("trust.example.org".to_string(), master_key2);
        let plaintext = b"secret";

        let encrypted = adapter1.encrypt_private_key(plaintext).unwrap();
        let result = adapter2.decrypt_private_key(&encrypted);

        assert!(result.is_err());
    }

    #[test]
    fn decryption_fails_with_tampered_data() {
        let master_key = vec![0x42u8; 32];
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), master_key);
        let plaintext = b"original secret";

        let mut encrypted = adapter.encrypt_private_key(plaintext).unwrap();

        // Tamper with the ciphertext (last byte of tag)
        let last_idx = encrypted.len() - 1;
        encrypted[last_idx] ^= 0xFF;

        let result = adapter.decrypt_private_key(&encrypted);
        assert!(result.is_err());
    }
}
