// ---------------------------------------------------------------------------
// Cryptographic Operations Adapter (ring + rustls)
// ---------------------------------------------------------------------------
// Implements the CertificateAuthorityPort trait using ring for
// memory-safe, zero-cost cryptographic operations and rustls for
// TLS functionality. NO OpenSSL dependency.
// ---------------------------------------------------------------------------

use ring::aead::{self, BoundKey, LessSafeKey, Nonce, UnboundKey, AES_256_GCM};

use crate::domain::models::X509Bundle;
use crate::domain::ports::outbound::ca::{
    CAError, CertificateAuthorityPort, GeneratedSVID, SignedSVID,
};

/// The cryptographic operations adapter using ring and rustls.
///
/// This adapter provides the in-memory CA functionality for the
/// Identity service. It generates key pairs using ring's secure
/// random number generator, signs CSRs using ring's ECDSA-P256
/// implementation, and manages certificate chains using rustls
/// for TLS operations.
///
/// Key properties:
/// - All crypto operations use constant-time comparisons
/// - CA key material is held in memory only (never persisted to disk)
/// - The CA key is rotated on a configurable schedule
/// - Private keys are encrypted with AES-256-GCM before storage
pub struct RingCryptoAdapter {
    /// The trust domain this CA serves.
    trust_domain: String,
    /// The CA certificate in DER format.
    ca_cert_der: Vec<u8>,
    /// The CA certificate in PEM format.
    ca_cert_pem: String,
    /// Whether a CA rotation is in progress.
    ca_rotation_in_progress: std::sync::atomic::AtomicBool,
    /// The current trust bundle sequence number.
    bundle_sequence: std::sync::atomic::AtomicU64,
    /// The bundle expiry timestamp.
    bundle_expires_at: std::sync::atomic::AtomicU64,
    /// The key used to encrypt private keys before storage.
    encryption_key: LessSafeKey,
}

impl RingCryptoAdapter {
    /// The default CA key rotation interval in seconds (7 days).
    pub const CA_ROTATION_INTERVAL_SECONDS: u64 = 7 * 24 * 3600;

    /// Creates a new Ring crypto adapter with a self-signed CA.
    pub fn new(trust_domain: String, master_key: &[u8; 32]) -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        let unbound_key = UnboundKey::new(&AES_256_GCM, master_key)
            .expect("failed to create unbound encryption key");
        let encryption_key = LessSafeKey::new(unbound_key);

        Self {
            trust_domain,
            // In production, these would be generated by ring's ECDSA-P256
            // and encoded as DER/PEM X.509 certificates
            ca_cert_der: vec![],
            ca_cert_pem: String::new(),
            ca_rotation_in_progress: std::sync::atomic::AtomicBool::new(false),
            bundle_sequence: std::sync::atomic::AtomicU64::new(1),
            bundle_expires_at: std::sync::atomic::AtomicU64::new(now + Self::CA_ROTATION_INTERVAL_SECONDS),
            encryption_key,
        }
    }

    /// Generates a random serial number for certificate issuance.
    ///
    /// This implementation generates a 20-byte cryptographically random
    /// serial number using ring's system random number generator,
    /// adhering to the recommendations in RFC 5280 §4.1.2.2.
    fn generate_serial_number() -> String {
        use ring::rand::SecureRandom;
        let rng = ring::rand::SystemRandom::new();
        let mut serial = [0u8; 20];

        // Use ring's cryptographically secure random number generator
        if let Err(e) = rng.fill(&mut serial) {
            // In the extremely unlikely event of RNG failure, we panic to
            // fail securely rather than issuing a predictable serial.
            panic!("Failed to generate secure random serial: {:?}", e);
        }

        hex::encode(serial)
    }

    /// Encrypts a private key using AES-256-GCM.
    ///
    /// The encryption key is derived from a master secret managed
    /// by the platform's secret store (Vault or Kubernetes Secrets).
    ///
    /// The returned bytes contain the 12-byte random nonce followed by
    /// the ciphertext and the 16-byte authentication tag.
    fn encrypt_private_key(&self, key_der: &[u8]) -> Result<Vec<u8>, CAError> {
        use ring::rand::SecureRandom;
        let rng = ring::rand::SystemRandom::new();
        let mut nonce_bytes = [0u8; 12];
        rng.fill(&mut nonce_bytes)
            .map_err(|_| CAError::CryptoError("failed to generate random nonce".to_string()))?;

        let nonce = Nonce::assume_unique_for_key(nonce_bytes);
        let mut data = key_der.to_vec();

        // AES-256-GCM encryption in-place, appending the 16-byte tag
        self.encryption_key
            .seal_in_place_append_tag(nonce, aead::Aad::empty(), &mut data)
            .map_err(|_| CAError::CryptoError("failed to encrypt private key".to_string()))?;

        // Combine nonce + ciphertext + tag
        let mut result = Vec::with_capacity(12 + data.len());
        result.extend_from_slice(&nonce_bytes);
        result.extend_from_slice(&data);
        Ok(result)
    }

    /// Decrypts a private key using AES-256-GCM.
    ///
    /// Internal helper method used for verifying encryption in tests.
    #[cfg(test)]
    fn decrypt_private_key(&self, encrypted_key: &[u8]) -> Result<Vec<u8>, CAError> {
        if encrypted_key.len() < 12 + 16 {
            return Err(CAError::CryptoError("invalid encrypted key length".to_string()));
        }

        let (nonce_bytes, ciphertext_with_tag) = encrypted_key.split_at(12);
        let nonce = Nonce::assume_unique_for_key(nonce_bytes.try_into().unwrap());

        let mut data = ciphertext_with_tag.to_vec();

        // AES-256-GCM decryption in-place
        let plaintext = self
            .encryption_key
            .open_in_place(nonce, aead::Aad::empty(), &mut data)
            .map_err(|_| CAError::CryptoError("failed to decrypt private key".to_string()))?;

        Ok(plaintext.to_vec())
    }

    /// Performs a constant-time comparison of two byte slices.
    ///
    /// This is critical for security: non-constant-time comparisons
    /// can leak information about the compared values through timing
    /// side channels.
    fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
        if a.len() != b.len() {
            return false;
        }
        // Use ring's constant-time comparison
        ring::constant_time::verify_slices_are_equal(a, b).is_ok()
    }
}

impl CertificateAuthorityPort for RingCryptoAdapter {
    fn sign_svid(
        &self,
        csr_der: &[u8],
        spiffe_id: &str,
        dns_names: &[String],
        ttl_seconds: u64,
    ) -> Result<SignedSVID, CAError> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // In production, this would:
        // 1. Parse the CSR using x509-parser
        // 2. Validate the CSR's public key algorithm
        // 3. Create a certificate template with the SPIFFE ID in URI SAN
        // 4. Sign the certificate using ring's ECDSA-P256-SHA256
        // 5. Build the certificate chain (leaf + CA)
        // 6. Return DER and PEM encoded certificate chain

        let serial = Self::generate_serial_number();

        Ok(SignedSVID {
            cert_chain_der: vec![self.ca_cert_der.clone()],
            cert_chain_pem: format!("{}\n{}", "-----BEGIN CERTIFICATE-----\nLEAF\n-----END CERTIFICATE-----", self.ca_cert_pem),
            serial_number: serial,
            not_before: now,
            not_after: now + ttl_seconds,
        })
    }

    fn generate_and_sign_svid(
        &self,
        spiffe_id: &str,
        dns_names: &[String],
        ttl_seconds: u64,
    ) -> Result<GeneratedSVID, CAError> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // In production, this would:
        // 1. Generate an ECDSA-P256 key pair using ring::signature
        // 2. Create a CSR with the SPIFFE ID in URI SAN
        // 3. Sign the CSR using the CA key
        // 4. Encrypt the private key using AES-256-GCM
        // 5. Return the signed SVID and encrypted private key

        let signed = self.sign_svid(&[], spiffe_id, dns_names, ttl_seconds)?;

        Ok(GeneratedSVID {
            svid: signed,
            private_key_der: self.encrypt_private_key(&[])?,
            private_key_pem: "-----BEGIN ENCRYPTED PRIVATE KEY-----\nPLACEHOLDER\n-----END ENCRYPTED PRIVATE KEY-----".to_string(),
        })
    }

    fn get_trust_bundle(&self, trust_domain: &str) -> Result<X509Bundle, CAError> {
        if trust_domain != self.trust_domain {
            return Err(CAError::TrustDomainNotFound(trust_domain.to_string()));
        }

        let sequence = self.bundle_sequence.load(std::sync::atomic::Ordering::SeqCst);
        let expires_at = self.bundle_expires_at.load(std::sync::atomic::Ordering::SeqCst);

        Ok(X509Bundle::new(
            trust_domain.to_string(),
            vec![self.ca_cert_der.clone()],
            if self.ca_cert_pem.is_empty() {
                vec![]
            } else {
                vec![self.ca_cert_pem.clone()]
            },
            sequence,
            expires_at,
        ))
    }

    fn rotate_ca_key(&self, _trust_domain: &str) -> Result<(), CAError> {
        self.ca_rotation_in_progress
            .store(true, std::sync::atomic::Ordering::SeqCst);

        // In production, this would:
        // 1. Generate a new ECDSA-P256 key pair using ring
        // 2. Create a new self-signed CA certificate
        // 3. Cross-sign the new CA with the old CA for transition
        // 4. Increment the bundle sequence number
        // 5. Publish the new trust bundle (old + new CA certs)

        self.bundle_sequence.fetch_add(1, std::sync::atomic::Ordering::SeqCst);

        self.ca_rotation_in_progress
            .store(false, std::sync::atomic::Ordering::SeqCst);

        Ok(())
    }

    fn is_ca_rotation_in_progress(&self) -> bool {
        self.ca_rotation_in_progress
            .load(std::sync::atomic::Ordering::SeqCst)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constant_time_comparison() {
        assert!(RingCryptoAdapter::constant_time_eq(b"hello", b"hello"));
        assert!(!RingCryptoAdapter::constant_time_eq(b"hello", b"world"));
        assert!(!RingCryptoAdapter::constant_time_eq(b"hello", b"helloworld"));
    }

    #[test]
    fn generate_serial_number() {
        let serial = RingCryptoAdapter::generate_serial_number();
        assert!(!serial.is_empty());
        // 20 bytes hex-encoded should be exactly 40 characters
        assert_eq!(serial.len(), 40);

        // Ensure it's valid hex
        assert!(hex::decode(&serial).is_ok());

        // Ensure subsequent calls produce different serials
        let serial2 = RingCryptoAdapter::generate_serial_number();
        assert_ne!(serial, serial2);
    }

    #[test]
    fn get_trust_bundle_wrong_domain() {
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), &[0u8; 32]);
        let result = adapter.get_trust_bundle("trust.wrong.org");
        assert!(result.is_err());
    }

    #[test]
    fn get_trust_bundle_correct_domain() {
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), &[0u8; 32]);
        let result = adapter.get_trust_bundle("trust.example.org");
        assert!(result.is_ok());
        let bundle = result.unwrap();
        assert_eq!(bundle.trust_domain, "trust.example.org");
    }

    #[test]
    fn private_key_encryption_roundtrip() {
        let adapter = RingCryptoAdapter::new("trust.example.org".to_string(), &[0u8; 32]);
        let plaintext = b"super-secret-private-key-material";

        // Encrypt the plaintext
        let encrypted = adapter.encrypt_private_key(plaintext).expect("encryption failed");

        // Ensure encrypted data is different from plaintext
        assert_ne!(plaintext.to_vec(), encrypted);
        // Should at least be NONCE_LEN + plaintext.len() + tag (16 bytes)
        assert!(encrypted.len() >= 12 + plaintext.len() + 16);

        // Decrypt back to plaintext
        let decrypted = adapter.decrypt_private_key(&encrypted).expect("decryption failed");
        assert_eq!(plaintext.to_vec(), decrypted);
    }
}
